spring:
  application:
    name: currency-exchange
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  retry:
    instances:
      default:
        maxAttempts: 5
        waitDuration: 1s
        enableExponentialBackoff: true
  ratelimiter:
    instances:
      default:
        limitForPeriod: 2
        limitRefreshPeriod: 10s
  bulkhead:
    instances:
      default:
        maxConcurrentCalls: 10